
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5246:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    
